// Generated by scripts/generate-logo-art.py from imgs/Hya icon v7.png — do not edit by hand.
// Each character is a 2x2 sub-pixel quadrant/half-block glyph; space = transparent.
export type LogoArt = { color: string; rows: string[] }
export const EPILOGUE_ART: LogoArt = {
  color: "#006af7",
  rows: [
    "▄▄▄ ▟█▌         ",
    "▜██▖▐█▙         ",
    "▝██████▐█▗█▌▗▄▄ ",
    " ▜██▀██▐█▟███▀██",
    " ▐██ ██ ▛██▝████",
    "  ▝    ▐██▘     ",
  ],
}
