use crate::contracts::BindingId;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommandCatalogEntry {
    pub config_key: &'static str,
    pub command: BindingId,
}

pub const COMMAND_MAP: &[(&str, &str)] = &[
    ("app_exit", "app.exit"),
    ("app_debug", "app.debug"),
    ("app_console", "app.console"),
    ("app_heap_snapshot", "app.heap_snapshot"),
    ("app_toggle_animations", "app.toggle.animations"),
    ("app_toggle_file_context", "app.toggle.file_context"),
    ("app_toggle_diffwrap", "app.toggle.diffwrap"),
    ("app_toggle_paste_summary", "app.toggle.paste_summary"),
    (
        "app_toggle_session_directory_filter",
        "app.toggle.session_directory_filter",
    ),
    ("command_list", "command.palette.show"),
    ("help_show", "help.show"),
    ("docs_open", "docs.open"),
    ("diff_close", "diff.close"),
    ("diff_toggle", "diff.toggle"),
    ("diff_expand", "diff.expand"),
    ("diff_expand_all", "diff.expand_all"),
    ("diff_collapse", "diff.collapse"),
    ("diff_switch_focus", "diff.switch_focus"),
    ("diff_next_hunk", "diff.next_hunk"),
    ("diff_previous_hunk", "diff.previous_hunk"),
    ("diff_next_file", "diff.next_file"),
    ("diff_previous_file", "diff.previous_file"),
    ("diff_toggle_file_tree", "diff.toggle_file_tree"),
    ("diff_single_patch", "diff.single_patch"),
    ("diff_switch_source", "diff.switch_source"),
    ("diff_toggle_view", "diff.toggle_view"),
    ("diff_help", "diff.help"),
    ("editor_open", "prompt.editor"),
    ("theme_list", "theme.switch"),
    ("theme_switch_mode", "theme.switch_mode"),
    ("theme_mode_lock", "theme.mode.lock"),
    ("sidebar_toggle", "session.sidebar.toggle"),
    ("scrollbar_toggle", "session.toggle.scrollbar"),
    ("status_view", "hya.status"),
    ("session_export", "session.export"),
    ("session_copy", "session.copy"),
    ("session_new", "session.new"),
    ("session_list", "session.list"),
    ("session_timeline", "session.timeline"),
    ("session_fork", "session.fork"),
    ("session_rename", "session.rename"),
    ("session_delete", "session.delete"),
    ("session_interrupt", "session.interrupt"),
    ("session_background", "session.background"),
    ("session_compact", "session.compact"),
    ("session_toggle_timestamps", "session.toggle.timestamps"),
    (
        "session_toggle_generic_tool_output",
        "session.toggle.generic_tool_output",
    ),
    ("session_queued_prompts", "session.queued_prompts"),
    ("session_child_first", "session.child.first"),
    ("session_child_cycle", "session.child.next"),
    ("session_child_cycle_reverse", "session.child.previous"),
    ("session_parent", "session.parent"),
    ("session_pin_toggle", "session.pin.toggle"),
    ("session_quick_switch_1", "session.quick_switch.1"),
    ("session_quick_switch_2", "session.quick_switch.2"),
    ("session_quick_switch_3", "session.quick_switch.3"),
    ("session_quick_switch_4", "session.quick_switch.4"),
    ("session_quick_switch_5", "session.quick_switch.5"),
    ("session_quick_switch_6", "session.quick_switch.6"),
    ("session_quick_switch_7", "session.quick_switch.7"),
    ("session_quick_switch_8", "session.quick_switch.8"),
    ("session_quick_switch_9", "session.quick_switch.9"),
    ("pane_roster", "pane.roster"),
    ("pane_channels", "pane.channels"),
    ("pane_close", "pane.close"),
    ("pane_cycle", "pane.cycle"),
    ("pane_focus_main", "pane.focus.main"),
    ("stash_delete", "stash.delete"),
    ("model_provider_list", "model.dialog.provider"),
    ("model_favorite_toggle", "model.dialog.favorite"),
    ("model_list", "model.list"),
    ("permission_yolo_switch", "permission.yolo.switch"),
    ("model_cycle_recent", "model.cycle_recent"),
    ("model_cycle_recent_reverse", "model.cycle_recent_reverse"),
    ("model_cycle_favorite", "model.cycle_favorite"),
    (
        "model_cycle_favorite_reverse",
        "model.cycle_favorite_reverse",
    ),
    ("mcp_list", "mcp.list"),
    ("provider_connect", "provider.connect"),
    ("console_org_switch", "console.org.switch"),
    ("agent_list", "agent.list"),
    ("agent_cycle", "agent.cycle"),
    ("agent_cycle_reverse", "agent.cycle.reverse"),
    ("variant_cycle", "variant.cycle"),
    ("variant_list", "variant.list"),
    ("messages_page_up", "session.page.up"),
    ("messages_page_down", "session.page.down"),
    ("messages_line_up", "session.line.up"),
    ("messages_line_down", "session.line.down"),
    ("messages_half_page_up", "session.half.page.up"),
    ("messages_half_page_down", "session.half.page.down"),
    ("messages_first", "session.first"),
    ("messages_last", "session.last"),
    ("messages_next", "session.message.next"),
    ("messages_previous", "session.message.previous"),
    ("messages_last_user", "session.messages_last_user"),
    ("messages_copy", "messages.copy"),
    ("messages_undo", "session.undo"),
    ("messages_redo", "session.redo"),
    ("messages_toggle_conceal", "session.toggle.conceal"),
    ("tool_details", "session.toggle.actions"),
    ("display_thinking", "session.toggle.thinking"),
    ("prompt_submit", "prompt.submit"),
    ("prompt_editor_context_clear", "prompt.editor_context.clear"),
    ("prompt_skills", "prompt.skills"),
    ("prompt_stash", "prompt.stash"),
    ("prompt_stash_pop", "prompt.stash.pop"),
    ("prompt_stash_list", "prompt.stash.list"),
    ("workspace_set", "workspace.set"),
    ("input_clear", "prompt.clear"),
    ("input_paste", "prompt.paste"),
    ("input_submit", "input.submit"),
    ("input_newline", "input.newline"),
    ("input_move_left", "input.move.left"),
    ("input_move_right", "input.move.right"),
    ("input_move_up", "input.move.up"),
    ("input_move_down", "input.move.down"),
    ("input_select_left", "input.select.left"),
    ("input_select_right", "input.select.right"),
    ("input_select_up", "input.select.up"),
    ("input_select_down", "input.select.down"),
    ("input_line_home", "input.line.home"),
    ("input_line_end", "input.line.end"),
    ("input_select_line_home", "input.select.line.home"),
    ("input_select_line_end", "input.select.line.end"),
    ("input_visual_line_home", "input.visual.line.home"),
    ("input_visual_line_end", "input.visual.line.end"),
    (
        "input_select_visual_line_home",
        "input.select.visual.line.home",
    ),
    (
        "input_select_visual_line_end",
        "input.select.visual.line.end",
    ),
    ("input_buffer_home", "input.buffer.home"),
    ("input_buffer_end", "input.buffer.end"),
    ("input_select_buffer_home", "input.select.buffer.home"),
    ("input_select_buffer_end", "input.select.buffer.end"),
    ("input_delete_line", "input.delete.line"),
    ("input_delete_to_line_end", "input.delete.to.line.end"),
    ("input_delete_to_line_start", "input.delete.to.line.start"),
    ("input_backspace", "input.backspace"),
    ("input_delete", "input.delete"),
    ("input_undo", "input.undo"),
    ("input_redo", "input.redo"),
    ("input_word_forward", "input.word.forward"),
    ("input_word_backward", "input.word.backward"),
    ("input_select_word_forward", "input.select.word.forward"),
    ("input_select_word_backward", "input.select.word.backward"),
    ("input_delete_word_forward", "input.delete.word.forward"),
    ("input_delete_word_backward", "input.delete.word.backward"),
    ("input_select_all", "input.select.all"),
    ("history_previous", "prompt.history.previous"),
    ("history_next", "prompt.history.next"),
    ("terminal_suspend", "terminal.suspend"),
    ("terminal_title_toggle", "terminal.title.toggle"),
    ("tips_toggle", "tips.toggle"),
    ("plugin_manager", "plugins.list"),
    ("plugin_install", "plugins.install"),
    ("which_key_toggle", "which-key.toggle"),
    ("which_key_layout_toggle", "which-key.layout.toggle"),
    ("which_key_pending_toggle", "which-key.pending.toggle"),
    ("which_key_group_previous", "which-key.group.previous"),
    ("which_key_group_next", "which-key.group.next"),
    ("which_key_scroll_up", "which-key.scroll.up"),
    ("which_key_scroll_down", "which-key.scroll.down"),
    ("which_key_page_up", "which-key.page.up"),
    ("which_key_page_down", "which-key.page.down"),
    ("which_key_home", "which-key.home"),
    ("which_key_end", "which-key.end"),
];

#[must_use]
pub fn command_mapping() -> &'static [(&'static str, &'static str)] {
    COMMAND_MAP
}

#[must_use]
pub fn canonical_command_name(config_key: &str) -> &str {
    COMMAND_MAP
        .iter()
        .find_map(|(key, command)| (*key == config_key).then_some(*command))
        .unwrap_or(config_key)
}

#[must_use]
pub fn canonical_command(config_key: &str) -> BindingId {
    BindingId(canonical_command_name(config_key).to_owned())
}

#[must_use]
pub fn command_catalog() -> Vec<CommandCatalogEntry> {
    COMMAND_MAP
        .iter()
        .map(|(config_key, command)| CommandCatalogEntry {
            config_key,
            command: BindingId((*command).to_owned()),
        })
        .collect()
}
