//! Display-offset arithmetic for the prompt editor — a faithful port of
//! the upstream TUI prompt/display.ts.
//!
//! Parity is VERIFIED byte-for-byte against the TS implementation via
//! `fixtures/display_golden.json`, generated by `scripts/dump-display.ts` (PLAN.md R-4).
//! Key quirk preserved: a newline counts as display width **1** (TS textarea offset),
//! whereas raw display-width libraries count it as 0.

use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

/// Grapheme width matching `Bun.stringWidth`: `\n` => 1 (TS override), other control chars
/// (e.g. tab) => 0 — `unicode-width` would give tab 1, breaking display-offset parity.
fn segment_width(seg: &str) -> usize {
    if seg == "\n" {
        return 1;
    }
    if let Some(c) = seg.chars().next() {
        if seg.chars().count() == 1 && c.is_control() {
            return 0;
        }
    }
    UnicodeWidthStr::width(seg)
}

/// Total display width of `value` (newlines count as 1). Mirrors `promptOffsetWidth`.
#[must_use]
pub fn prompt_offset_width(value: &str) -> usize {
    value.graphemes(true).map(segment_width).sum()
}

/// Byte index into `value` at the grapheme boundary reaching display `offset`.
/// Mirrors `displayOffsetIndex` (returns `value.len()` when offset is past the end).
fn display_offset_index(value: &str, offset: usize) -> usize {
    if offset == 0 {
        return 0;
    }
    let mut width = 0usize;
    for (idx, seg) in value.grapheme_indices(true) {
        let next = width + segment_width(seg);
        if next > offset {
            return idx;
        }
        width = next;
    }
    value.len()
}

/// Slice `value` by display offsets `[start, end)`. Mirrors `displaySlice`.
#[must_use]
pub fn display_slice(value: &str, start: usize, end: usize) -> &str {
    let s = display_offset_index(value, start);
    let e = display_offset_index(value, end);
    &value[s..e]
}

/// The grapheme at display `offset`, if any. Mirrors `displayCharAt`.
#[must_use]
pub fn display_char_at(value: &str, offset: usize) -> Option<&str> {
    let mut width = 0usize;
    for seg in value.graphemes(true) {
        let next = width + segment_width(seg);
        if offset == width || offset < next {
            return Some(seg);
        }
        width = next;
    }
    None
}

/// Nearest valid `@` mention-trigger display-index before `offset`. Mirrors
/// `mentionTriggerIndex`: the `@` must be at start or preceded by whitespace, and the
/// query (from `@` to cursor) must contain no whitespace.
#[must_use]
pub fn mention_trigger_index(value: &str, offset: usize) -> Option<usize> {
    let text = display_slice(value, 0, offset);
    let at = text.rfind('@')?;
    let before = text[..at].chars().next_back();
    let query = &text[at..];
    let before_ok = before.is_none_or(char::is_whitespace);
    let query_ok = !query.chars().any(char::is_whitespace);
    if before_ok && query_ok {
        Some(prompt_offset_width(&text[..at]))
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn newline_counts_as_width_one() {
        assert_eq!(prompt_offset_width("a\nb"), 3);
    }

    #[test]
    fn mention_basic() {
        assert_eq!(mention_trigger_index("@file", 5), Some(0));
        assert_eq!(mention_trigger_index("look @src", 9), Some(5));
        assert_eq!(mention_trigger_index("email a@b", 9), None); // no ws before @
        assert_eq!(mention_trigger_index("@a b", 4), None); // whitespace in query
    }

    /// R-4 byte-for-byte parity gate against the real TS implementation.
    /// Generate the fixture with: `bun run scripts/dump-display.ts`.
    #[test]
    fn display_golden() {
        #[derive(serde::Deserialize)]
        struct Case {
            input: String,
            offset: usize,
            width: usize,
            slice: String,
            mention: Option<usize>,
        }
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../fixtures/display_golden.json"
        );
        let raw = std::fs::read_to_string(path)
            .expect("fixtures/display_golden.json missing — run `bun run scripts/dump-display.ts`");
        let cases: Vec<Case> = serde_json::from_str(&raw).expect("parse display_golden.json");
        assert!(!cases.is_empty(), "golden corpus is empty");
        for c in &cases {
            assert_eq!(
                prompt_offset_width(&c.input),
                c.width,
                "width for {:?}",
                c.input
            );
            assert_eq!(
                display_slice(&c.input, 0, c.offset),
                c.slice,
                "slice for {:?} @ {}",
                c.input,
                c.offset
            );
            assert_eq!(
                mention_trigger_index(&c.input, c.offset),
                c.mention,
                "mention for {:?} @ {}",
                c.input,
                c.offset
            );
        }
    }
}
