mod error;
mod footer_text;
mod identity;
mod keybindings;
mod overlays;
mod permission;
mod prompt;
mod prompt_attachments;
mod prompt_metadata;
mod question;
mod sidebar;
mod sidebar_agents;
mod sidebar_context;
mod sidebar_files;
mod sidebar_footer;
mod sidebar_format;
mod sidebar_header;
mod sidebar_runtime;
mod sidebar_stats;
mod status;
mod transcript;
mod transcript_diff;
mod transcript_metadata;
mod transcript_output;
mod transcript_pending;
mod transcript_reasoning;
mod transcript_scroll;
mod transcript_text;
mod transcript_tool_status;
mod transcript_tools;
#[cfg(test)]
mod transcript_tools_tests;

pub use keybindings::render_keybindings;
pub use overlays::{render_dialog, render_picker};
pub use permission::render_permission;
pub use prompt::{prompt_cursor, prompt_height, render_footer, render_prompt};
pub use question::render_question;
pub use sidebar::render_sidebar;
pub use status::render_runtime_status;
pub use transcript::render_timeline;
