/** Text of the `/help` view. Keep in step with the registry in native.ts. */
export const helpText = [
  "Type a prompt to create a session (if needed) and start a turn.",
  "/ opens the command menu (fuzzy filter, Up/Down select, Tab completes the name; Enter runs a command whose",
  "argument hint is missing or [bracketed] (optional), else completes the name and waits for the argument).",
  "Commands come from three sources: this TUI (local), the backend catalog (custom commands), and skills;",
  "a local name always wins a clash with a backend name.",
  "", "/new [agent] [model]   Create a session", "/sessions             Refresh session list",
  "/open <id|number>     Open a session; a subagent's session opens read-only (Esc returns), also by clicking its task card",
  "/models               List models", "/model [provider/model] Change current session model, or show it with no argument",
  "/agent [name]         Change current session agent, or show it with no argument",
  "/rename <title>       Rename the current session",
  "/permissions [mode]   Pick the permission mode (manual, yolo, bundle modes), or set it directly (Shift+Tab cycles)",
  "/workflows            List workflows",
  "/keys                 List saved provider key names", "/key set <provider>   Enter a key in a concealed prompt",
  "/login <provider>     Alias for /key set", "/key remove <provider> Delete a saved key",
  "/workflow select <name> | /workflow run [name]", "/interactions         Show pending permissions and questions",
  "/approve <id> | /deny <id> | /answer <id> <text>   (keyboard fallback of the prompt)", "/cancel               Cancel current turn (Esc)", "/refresh              Refresh all views",
  "/sidebar [on|off]     Show or hide the sidebar (Ctrl+B)", "/thinking [on|off]    Expand or collapse reasoning (Ctrl+O)",
  "/tools [on|off]       Expand or collapse tool call cards (Ctrl+G); a click toggles one card",
  "/compact              Compact the session's context now", "/summarize            Summarize the session into a new message",
  "/todos                Show the session's todo list", "/status               Show connection, version, directory, session, agent, model, mode",
  "/init, /review        Server built-in commands (backend command catalog)",
  "/<skill> [args]       Run a skill as a command turn (backend catalog, source \"skill\")",
  "/api                  List all v1 HTTP operations", "/api METHOD /v1/path [JSON object]",
  "/exit, /quit          Quit", "",
  "!<command>            Run a shell command in the session (ShellTurn)",
  "@<text>               Pick a file path to reference (Up/Down, Tab/Enter insert, Esc closes)", "",
  "Enter send · Ctrl+J or Alt+Enter newline (Shift+Enter where the terminal reports it) · Up/Down history",
  "Permission prompt (input empty): 1 allow once · 2 always allow · 3 deny · Up/Down + Enter · Esc denies",
  "Question prompt: 1-N pick an option · type an answer + Enter · Esc rejects",
  "Esc close a menu, else decline a shown prompt, else return from a subagent view, else cancel the running turn, else clear the input · Ctrl+C clear, twice quit · Ctrl+D quit on empty input",
  "Shift+Tab cycle permission mode manual → yolo → bundle modes (yolo asks to confirm once) · in an open list: move up",
  "Tab completes commands · Ctrl+R refresh · Ctrl+B sidebar · Ctrl+O thinking · Ctrl+G tool cards",
  "PgUp/PgDn scroll · Ctrl+Home/Ctrl+End top/bottom (Home/End when the input is empty)",
].join("\n")
