// Generated by scripts/generate-logo-art.py from docs/assets/hya-icon-8bit.png — do not edit by hand.
// Each character is a 2x2 sub-pixel quadrant/half-block glyph; space = transparent.
export type LogoArt = { color: string; rows: string[] }
export const LOGO_ART: LogoArt = {
  color: "#2c8aee",
  rows: [
    "███  ▐██▌                 ",
    "███  ▐██▌ ▄▄▖ ▗▄▄▖ ▗▄▄▄▄▖ ",
    "████████▌ ██▌ ▐██▌ ▝▀▀▀██▙",
    "███▀▀▜██▌ ██▌ ▐██▌▗▟██████",
    "███  ▐██▌ ▀██████▌▜██▄▄███",
    "▀▀▀  ▝▀▀▘     ▐██▌ ▝▀▀▀▀▀▀",
    "          ▐█████▀         ",
  ],
}
