[package]
name = "hya-api"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[package.metadata.hya]
version-reference = "backend"

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
pbjson = { workspace = true }
pbjson-types = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }
