import { expect, hyaTui, test } from "./hya"

for (const width of [1100, 700]) {
  test(`commands float above the entire workspace and preserve drafts across resize (${width}px)`, async ({ tui, backend }, testInfo) => {
    const term = await tui(hyaTui(backend), { viewport: { width, height: 640 } })
    await term.waitForText("Message, !shell, or @file · / commands")
    await term.type("/layout split vertical jobs")
    await term.press("Enter")
    await term.waitForText("jobs · pane-6")
    await term.press("Alt+ArrowLeft")
    await expect.poll(async () => (await term.cell(0, (await term.find("jobs · pane-6"))!.col - 4))?.fg !== "#73c8e8").toBe(true)
    await term.type("message draft")
    await term.press("Alt+ArrowRight")
    await term.waitForText("▸ jobs · pane-6")
    await term.type("/")
    await term.waitForText("Commands")
    await term.waitForText("▸ /agent")
    const command = (await term.find("Commands"))!
    expect(command.row).toBe(2)
    const lines = await term.lines()
    const left = lines[command.row]!.lastIndexOf("┌", command.col)
    const { cols } = await term.size()
    expect(left).toBe(Math.max(0, Math.floor((cols - Math.min(96, cols - 4)) / 2)))
    expect(lines[command.row + 1]!.slice(left + 1).trimStart()).toMatch(/^\/\s/)
    expect((await term.find("▸ /agent"))!.row).toBe(command.row + 2)
    await term.attach(testInfo, "global-commands")
    await term.type("layout split")
    await term.waitForText("/layout split")
    await term.resize(width === 1100 ? 700 : 1100, 640)
    await term.waitForText("Commands")
    expect((await term.find("Commands"))!.row).toBe(2)
    await term.attach(testInfo, "global-commands-resized")
    await term.press("Escape")
    await expect.poll(() => term.find("Commands")).toBeNull()
    await term.press("Alt+ArrowLeft")
    await term.type(" continued")
    await term.waitForText("message draft continued")
    await term.press("Control+x")
    await term.type("/")
    await term.waitForText("/layout split")
    await term.press("Control+c")
    await expect.poll(() => term.find("Commands")).toBeNull()
  })
}
