import { expect, hyaTui, test } from "./hya"

test("keybinding settings expose nested completion and inspect exit without quitting", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("/keybindings ")
  await term.waitForText("/keybindings list")
  await term.waitForText("/keybindings show")
  await term.type("show qu")
  await term.waitForText("/keybindings show quit")
  await term.press("Tab")
  await term.press("Enter")
  await term.waitForText("Keybinding · quit")
  await term.waitForText("Command: /exit")
  await term.waitForText("again within 2 s")
  await term.attach(testInfo, "exit-binding")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybinding · quit")).toBeNull()
  await term.type("still running")
  await term.waitForText("still running")
})

test("the binding browser filters related commands, opens details and keeps the message draft", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("preserved message")
  await term.press("Control+x")
  await term.type("/keybindings")
  await term.press("Enter")
  await term.waitForText("Keybindings")
  await term.type("/tools")
  await term.waitForText(/toggleTools\s+\[conversation\]/)
  await term.waitForText("Keys: Ctrl+G")
  await term.attach(testInfo, "filtered-bindings")
  await term.press("Enter")
  await term.waitForText("Keybinding · toggleTools")
  await term.waitForText("Inspection only · Esc closes")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybinding · toggleTools")).toBeNull()
  await term.type(" continued")
  await term.waitForText("preserved message continued")
})

test("keybinding settings open from Sessions and restore that pane's key ownership", async ({ tui, backend }) => {
  const term = await tui(hyaTui(backend), { viewport: { width: 1500, height: 640 } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("preserved draft")
  await term.press("Control+x")
  await term.type("/layout focus pane-3")
  await term.press("Enter")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.type("/keybindings list workspace")
  await term.press("Enter")
  await term.waitForText("Keybindings · workspace")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybindings · workspace")).toBeNull()
  const sessions = (await term.find("Sessions"))!
  await expect.poll(async () => (await term.cell(sessions.row, sessions.col - 1))?.fg).toBe("#73c8e8")
  await term.type("no leak")
  await term.press("Alt+ArrowLeft")
  await term.type(" continues")
  await term.waitForText("preserved draft continues")
  expect(await term.text()).not.toContain("no leak")
})

test("the keybinding browser and action details fit about 80 columns", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend), { viewport: { width: 690, height: 640 } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("/keybindings list conversation")
  await term.press("Enter")
  await term.waitForText("Keybindings · conversation")
  await term.type("toggleTools")
  await term.waitForText("Keys: Ctrl+G")
  const { cols } = await term.size()
  expect(cols).toBeLessThanOrEqual(84)
  for (const line of await term.lines()) expect(line.length).toBeLessThanOrEqual(cols)
  await term.press("Enter")
  await term.waitForText("Keybinding · toggleTools")
  await term.waitForText("Conversation focus only")
  await term.attach(testInfo, "keybinding-narrow")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybinding · toggleTools")).toBeNull()
})
