import { expect, hyaTui, test } from "./hya"
import { readFile } from "node:fs/promises"
import { join } from "node:path"
import type { Tui } from "./harness"

async function command(term: Tui, text: string): Promise<void> {
  await term.type(text)
  await term.press("Enter")
}

async function closeModal(term: Tui, title: string): Promise<void> {
  await term.press("Escape")
  await expect.poll(() => term.find(title)).toBeNull()
}

test("keybinding settings expose nested completion and inspect exit without quitting", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("/keybind ")
  await term.waitForText("/keybind list")
  await term.waitForText("/keybind show")
  await term.type("show qu")
  await term.waitForText("/keybind show quit")
  await term.press("Tab")
  await term.press("Enter")
  await term.waitForText("Keybinding · quit")
  await term.waitForText("Command: /exit")
  await term.waitForText("press again within")
  await term.waitForText("2 s to quit and archive")
  await term.attach(testInfo, "exit-binding")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybinding · quit")).toBeNull()
  await term.type("still running")
  await term.waitForText("still running")
})

test("the binding browser filters related commands, opens details and keeps the message draft", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("preserved message")
  await term.press("Control+x")
  await term.type("/keybind")
  await term.press("Enter")
  await term.waitForText("Keybindings")
  await term.type("/exit")
  await term.waitForText(/Ctrl\+C\s+quit\s+workspace/)
  await term.attach(testInfo, "filtered-bindings")
  await term.press("Enter")
  await term.waitForText("Keybinding · quit")
  await term.waitForText("Inspection only · Esc closes")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybinding · quit")).toBeNull()
  await term.type(" continued")
  await term.waitForText("preserved message continued")
})

test("keybinding settings open from Sessions and restore that pane's key ownership", async ({ tui, backend }) => {
  const term = await tui(hyaTui(backend), { viewport: { width: 1500, height: 640 } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("preserved draft")
  await term.press("Control+x")
  await term.type("/layout focus pane-3")
  await term.press("Enter")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.type("/keybind list workspace")
  await term.press("Enter")
  await term.waitForText("Keybindings · workspace")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybindings · workspace")).toBeNull()
  const sessions = (await term.find("Sessions"))!
  await expect.poll(async () => (await term.cell(sessions.row, sessions.col - 1))?.fg).toBe("#73c8e8")
  await term.type("no leak")
  await term.press("Alt+ArrowLeft")
  await term.type(" continues")
  await term.waitForText("preserved draft continues")
  expect(await term.text()).not.toContain("no leak")
})

test("the keybinding browser and action details fit about 80 columns", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend), { viewport: { width: 690, height: 640 } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("/keybind list conversation")
  await term.press("Enter")
  await term.waitForText("Keybindings · conversation")
  await term.type("interrupt")
  await term.waitForText(/Esc\s+interrupt\s+conversation/)
  const { cols } = await term.size()
  expect(cols).toBeLessThanOrEqual(84)
  for (const line of await term.lines()) expect(line.length).toBeLessThanOrEqual(cols)
  await term.press("Enter")
  await term.waitForText("Keybinding · interrupt")
  await term.waitForText("Conversation focus only")
  await term.attach(testInfo, "keybinding-narrow")
  await term.press("Escape")
  await expect.poll(() => term.find("Keybinding · interrupt")).toBeNull()
})

test("a saved multiword command runs through the registry and survives a restarted frontend", async ({ tui, backend }, testInfo) => {
  const prefs = join(backend.dir, "tui-settings.json")
  const options = { viewport: { width: 1500, height: 640 }, env: { HYA_TUI_CONFIG: prefs } }
  let term = await tui(hyaTui(backend), options)
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("draft survives")
  await term.press("Control+x")
  await command(term, "/keybind set F6 /layout focus pane-3")
  await term.waitForText("Keybind saved · F6")
  await term.waitForText("Command: /layout focus pane-3")
  await term.attach(testInfo, "saved-command")
  await closeModal(term, "Keybind saved · F6")
  expect(JSON.parse(await readFile(prefs, "utf8")).keybindings).toEqual({ F6: { command: "/layout focus pane-3", scope: "workspace" } })
  await term.press("F6")
  let sessions = (await term.find("Sessions"))!
  await expect.poll(async () => (await term.cell(sessions.row, sessions.col - 1))?.fg).toBe("#73c8e8")
  await term.press("Alt+ArrowLeft")
  await term.type(" continues")
  await term.waitForText("draft survives continues")
  term = await tui(hyaTui(backend), options)
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.press("F6")
  sessions = (await term.find("Sessions"))!
  await expect.poll(async () => (await term.cell(sessions.row, sessions.col - 1))?.fg).toBe("#73c8e8")
})

test("conversation-scoped command shortcuts stay inactive in Sessions", async ({ tui, backend }) => {
  const term = await tui(hyaTui(backend), { viewport: { width: 1500, height: 640 } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await command(term, "/keybind set F6 --scope conversation /sidebar off")
  await term.waitForText("Keybind saved · F6")
  await term.waitForText("Custom shortcut (conversation)")
  await closeModal(term, "Keybind saved · F6")
  await command(term, "/layout focus pane-3")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.press("F6")
  await term.type("/")
  await term.waitForText("Commands")
  expect(await term.find("Sessions")).not.toBeNull()
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.press("Alt+ArrowLeft")
  await term.press("F6")
  await expect.poll(() => term.find("Sessions")).toBeNull()
})

test("invalid commands are visible, modals retain key ownership, and unset removes the shortcut", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await command(term, "/keybind set Alt+G /help")
  await term.waitForText("Keybind saved · Alt+G")
  await closeModal(term, "Keybind saved · Alt+G")
  await command(term, "/keybind set F7 invalid")
  await term.waitForText("Keybind · not saved")
  await term.waitForText("single slash command")
  await term.attach(testInfo, "conflict-error")
  await term.press("Alt+g")
  expect(await term.find("Help · keys and commands")).toBeNull()
  await closeModal(term, "Keybind · not saved")
  await term.press("Alt+g")
  await term.waitForText("Help · keys and commands")
  await term.type("Alt+G")
  await term.waitForText("custom /keybind shortcut")
  await closeModal(term, "Help · keys and commands")
  await command(term, "/keybind unset Alt+G")
  await term.waitForText("Keybind unset")
  await closeModal(term, "Keybind unset")
  await term.press("Alt+g")
  await term.type("/")
  await term.waitForText("Commands")
  expect(await term.find("Help · keys and commands")).toBeNull()
})


test("optional defaults are inactive and released keys accept custom commands", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend), { env: { HYA_TUI_CONFIG: join(backend.dir, "essential-keys.json") } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.press("Shift+Tab")
  expect(await term.find("Enable yolo?")).toBeNull()
  await term.press("F4")
  expect(await term.find("No pending request in another session")).toBeNull()
  await command(term, "/keybind show toggleTools")
  await term.waitForText("unassigned")
  await closeModal(term, "Keybinding · toggleTools")
  await command(term, "/keybind set Ctrl+G /tools on")
  await term.waitForText("Keybind saved · Ctrl+G")
  await closeModal(term, "Keybind saved · Ctrl+G")
  await term.press("Control+g")
  await term.press("Control+x")
  await command(term, "/tools off")
  await term.type("draft")
  await term.press("Control+x")
  await term.type("u")
  await term.waitForText("draftu")
  await term.attach(testInfo, "essential-keys")
})


test("unset completes and persistently frees a reclaimed Ctrl+Home shortcut", async ({ tui, backend }, testInfo) => {
  const prefs = join(backend.dir, "unset-settings.json")
  const options = { env: { HYA_TUI_CONFIG: prefs } }
  let term = await tui(hyaTui(backend), options)
  await term.waitForText("Message, !shell, or @file · / commands")
  await command(term, "/keybind set Ctrl+Home /help")
  await term.waitForText("Keybind saved · Ctrl+Home")
  await closeModal(term, "Keybind saved · Ctrl+Home")
  await term.press("Control+Home")
  await term.waitForText("Help · keys and commands")
  await closeModal(term, "Help · keys and commands")
  await term.type("/keybind unset Ctrl+Ho")
  await term.waitForText("/keybind unset Ctrl+Home")
  await term.press("Tab")
  await term.press("Enter")
  await term.waitForText("Keybind unset")
  await term.attach(testInfo, "unset-result")
  expect(JSON.parse(await readFile(prefs, "utf8")).keybindings).toEqual({ "Ctrl+Home": null })
  await closeModal(term, "Keybind unset")
  term = await tui(hyaTui(backend), options)
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.press("Control+Home")
  await term.type("still editing")
  await term.waitForText("still editing")
  expect(await term.find("Help · keys and commands")).toBeNull()
})


for (const viewport of [{ width: 1100, height: 640 }, { width: 690, height: 640 }]) {
  test(`assigned shortcuts occupy aligned columns (${viewport.width}px)`, async ({ tui, backend }, testInfo) => {
    const term = await tui(hyaTui(backend), { viewport })
    await term.waitForText("Message, !shell, or @file · / commands")
    await command(term, "/keybind set F6 /tools on")
    await term.waitForText("Keybind saved · F6")
    await closeModal(term, "Keybind saved · F6")
    await command(term, "/keybind list")
    await term.waitForText("Shortcut")
    await term.waitForText("Action / command")
    await term.waitForText(/F6\s+\/tools on\s+conversation/)
    expect(await term.text()).not.toContain("unassigned")
    expect(await term.text()).not.toContain("Keys:")
    const shortcut = (await term.find("F6"))!
    const header = (await term.find("Shortcut"))!
    expect(shortcut.col).toBe(header.col)
    await term.type("Ctrl+C")
    await term.waitForText(/Ctrl\+C\s+quit\s+workspace/)
    await term.attach(testInfo, "binding-columns")
    for (const line of await term.lines()) expect(line.length).toBeLessThanOrEqual((await term.size()).cols)
  })
}


test("show without a target displays a usage error rather than choosing a binding", async ({ tui, backend }) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await command(term, "/keybind show")
  await term.waitForText("Keybind · error")
  await term.waitForText("Usage: /keybind show")
  await closeModal(term, "Keybind · error")
  await command(term, "/keybind show Ctrl+W")
  await term.waitForText("delete-word-backward")
})

test("Ctrl+W can close an auxiliary pane without a browser reservation", async ({ tui, backend }) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Message, !shell, or @file · / commands")
  await command(term, "/layout split vertical jobs")
  await term.waitForText("No active")
  await command(term, "/keybind set Ctrl+W /layout close")
  await term.waitForText("Keybind saved · Ctrl+W")
  await closeModal(term, "Keybind saved · Ctrl+W")
  await term.press("Control+w")
  await expect.poll(() => term.find("No active")).toBeNull()
  await term.type("editing works")
  await term.waitForText("editing works")
})

test("unset suppresses inherited editing, default exit and contextual picker actions; reset restores", async ({ tui, backend }, testInfo) => {
  const prefs = join(backend.dir, "removable.json")
  const options = { env: { HYA_TUI_CONFIG: prefs } }
  let term = await tui(hyaTui(backend), options)
  await term.waitForText("Message, !shell, or @file · / commands")
  for (const key of ["Ctrl+U", "Ctrl+C", "F2"]) {
    await command(term, `/keybind unset ${key}`)
    await term.waitForText("Keybind unset")
    await closeModal(term, "Keybind unset")
  }
  await term.type("kept draft")
  await term.press("Control+u")
  await term.press("Control+c")
  await term.press("Control+c")
  await term.waitForText("kept draft")
  await term.press("Control+x")
  await command(term, "/sessions")
  await term.waitForText("Sessions")
  await term.press("F2")
  expect(await term.find("New title")).toBeNull()
  await term.press("Escape")
  await expect.poll(() => term.find("Sessions · archived included")).toBeNull()
  await term.press("Control+x")
  await command(term, "/keybind show Ctrl+C")
  await term.waitForText("disabled")
  await term.attach(testInfo, "disabled-default")
  await closeModal(term, "Keybinding · Ctrl+C")
  expect(JSON.parse(await readFile(prefs, "utf8")).keybindings).toEqual({ "Ctrl+U": null, "Ctrl+C": null, F2: null })
  term = await tui(hyaTui(backend), options)
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("still kept")
  await term.press("Control+c")
  await term.waitForText("still kept")
  await term.press("Control+x")
  await command(term, "/keybind reset Ctrl+C")
  await term.waitForText("Keybind reset")
  await closeModal(term, "Keybind reset")
  await term.press("Control+c")
  await expect.poll(() => term.find("still kept")).toBeNull()
})
