import { expect, hyaTui, test } from "./hya"

for (const width of [1100, 700]) {
  test(`commands float above the entire workspace and preserve drafts across resize (${width}px)`, async ({ tui, backend }, testInfo) => {
    const term = await tui(hyaTui(backend), { viewport: { width, height: 640 } })
    await term.waitForText("Connected to hya")
    await term.type("/layout split vertical jobs")
    await term.press("Enter")
    await term.waitForText("jobs · pane-6")
    await term.press("Alt+ArrowLeft")
    await term.waitForText("pane-1 conversation")
    await term.type("message draft")
    await term.press("Alt+ArrowRight")
    await term.waitForText("pane-6 jobs")
    await term.type("/")
    await term.waitForText("Commands")
    const command = (await term.find("Commands"))!
    expect(command.row).toBe(2)
    const lines = await term.lines()
    const left = lines[command.row]!.lastIndexOf("┌", command.col)
    const { cols } = await term.size()
    expect(left).toBe(Math.max(0, Math.floor((cols - Math.min(96, cols - 4)) / 2)))
    await term.attach(testInfo, "global-commands")
    await term.type("layout split")
    await term.waitForText("/layout split")
    await term.resize(width === 1100 ? 700 : 1100, 640)
    await term.waitForText("Commands")
    expect((await term.find("Commands"))!.row).toBe(2)
    await term.attach(testInfo, "global-commands-resized")
    await term.press("Escape")
    await expect.poll(() => term.find("Commands")).toBeNull()
    await term.press("Alt+ArrowLeft")
    await term.type(" continued")
    await term.waitForText("message draft continued")
    await term.press("Control+x")
    await term.type("/")
    await term.waitForText("/layout split")
    await term.press("Control+c")
    await expect.poll(() => term.find("Commands")).toBeNull()
  })
}
