import { expect, hyaTui, test } from "./hya"

test("Sessions owns typing, editing, paste, and Enter while conversation draft survives", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend))
  await term.waitForText("Connected to hya")
  await term.type("preserved draft")
  await term.press("Control+x")
  await term.type("/layout focus pane-3")
  await term.press("Enter")
  await term.waitForText("pane-3 sessions")
  await term.type("leaked text")
  await term.type("/")
  await term.waitForText("Commands")
  expect(await term.text()).not.toContain("preserved draftleaked")
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.press("Backspace")
  await term.press("Enter")
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.page.evaluate(() => window.hyaTerm.term.paste("leaked paste"))
  await term.type("/")
  await term.waitForText("Commands")
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.press("Alt+ArrowLeft")
  await term.waitForText("pane-1 conversation")
  await term.type(" continues")
  await term.waitForText("preserved draft continues")
  expect(await term.text()).not.toContain("leaked")
  await term.attach(testInfo, "pane-routing")
})
