import { expect, hyaTui, test } from "./hya"

test("Sessions owns typing, editing, paste, and Enter while conversation draft survives", async ({ tui, backend }, testInfo) => {
  const term = await tui(hyaTui(backend), { viewport: { width: 1500, height: 640 } })
  await term.waitForText("Message, !shell, or @file · / commands")
  await term.type("preserved draft")
  await term.press("Control+x")
  await term.type("/layout focus pane-3")
  await term.press("Enter")
  await expect.poll(() => term.find("Commands")).toBeNull()
  const sessions = (await term.find("Sessions"))!
  await expect.poll(async () => (await term.cell(sessions.row, sessions.col - 1))?.fg).toBe("#73c8e8")
  await term.type("leaked text")
  await term.type("/")
  await term.waitForText("Commands")
  expect(await term.text()).not.toContain("preserved draftleaked")
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.press("Backspace")
  await term.press("Enter")
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.paste("leaked paste")
  await term.type("/")
  await term.waitForText("Commands")
  await term.press("Escape")
  await expect.poll(() => term.find("Commands")).toBeNull()
  await term.press("Alt+ArrowRight")
  await expect.poll(async () => (await term.cell(sessions.row, sessions.col - 1))?.fg).toBe("#405366")
  await term.type(" continues")
  await term.waitForText("preserved draft continues")
  expect(await term.text()).not.toContain("leaked")
  await term.attach(testInfo, "pane-routing")
})
