[package]
name = "hya"
version.workspace = true
edition = "2021"
license.workspace = true
default-run = "hya"

[[bin]]
name = "hya"
path = "src/main.rs"

[dev-dependencies]
axum = { workspace = true }
http-body-util = { workspace = true }
tower = { workspace = true }
hya-app = { workspace = true }
hya-sdk = { path = "../hya-sdk" }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }

[lints]
workspace = true
