use axum::Json;
use axum::Router;
use axum::routing::get;
use serde_json::{Map, Value, json};

use crate::ServerState;

pub(super) fn router() -> Router<ServerState> {
    Router::new()
        .route("/doc", get(doc))
        .route("/openapi.json", get(doc))
}

async fn doc() -> Json<Value> {
    let paths = paths(&[
        ("/doc", &["get"]),
        ("/openapi.json", &["get"]),
        ("/auth/{providerID}", &["put", "delete"]),
        ("/log", &["post"]),
        ("/global/health", &["get"]),
        ("/global/event", &["get"]),
        ("/global/config", &["get", "patch"]),
        ("/global/dispose", &["post"]),
        ("/global/upgrade", &["post"]),
        ("/event", &["get"]),
        ("/config", &["get", "patch"]),
        ("/config/providers", &["get"]),
        ("/provider", &["get"]),
        ("/provider/auth", &["get"]),
        ("/provider/{providerID}/oauth/authorize", &["post"]),
        ("/provider/{providerID}/oauth/callback", &["post"]),
        ("/find", &["get"]),
        ("/find/file", &["get"]),
        ("/find/symbol", &["get"]),
        ("/file", &["get"]),
        ("/file/content", &["get"]),
        ("/file/status", &["get"]),
        ("/path", &["get"]),
        ("/agent", &["get"]),
        ("/command", &["get"]),
        ("/skill", &["get"]),
        ("/lsp", &["get"]),
        ("/formatter", &["get"]),
        ("/vcs", &["get"]),
        ("/vcs/status", &["get"]),
        ("/vcs/diff", &["get"]),
        ("/vcs/diff/raw", &["get"]),
        ("/vcs/apply", &["post"]),
        ("/instance/dispose", &["post"]),
        ("/permission", &["get"]),
        ("/permission/{requestID}/reply", &["post"]),
        ("/question", &["get"]),
        ("/question/{requestID}/reply", &["post"]),
        ("/question/{requestID}/reject", &["post"]),
        ("/mcp", &["get", "post"]),
        ("/mcp/{name}/auth", &["post", "delete"]),
        ("/mcp/{name}/auth/authenticate", &["post"]),
        ("/mcp/{name}/auth/callback", &["post"]),
        ("/mcp/{name}/connect", &["post"]),
        ("/mcp/{name}/disconnect", &["post"]),
        ("/project", &["get"]),
        ("/project/current", &["get"]),
        ("/project/git/init", &["post"]),
        ("/project/{projectID}", &["patch"]),
        ("/project/{projectID}/directories", &["get"]),
        ("/pty/shells", &["get"]),
        ("/pty", &["get", "post"]),
        ("/pty/{ptyID}", &["get", "put", "delete"]),
        ("/pty/{ptyID}/connect-token", &["post"]),
        ("/pty/{ptyID}/connect", &["get"]),
        ("/session", &["get", "post"]),
        ("/session/status", &["get"]),
        ("/session/{sessionID}", &["get", "patch", "delete"]),
        ("/session/{sessionID}/children", &["get"]),
        ("/session/{sessionID}/todo", &["get"]),
        ("/session/{sessionID}/diff", &["get"]),
        ("/session/{sessionID}/fork", &["post"]),
        ("/session/{sessionID}/message", &["get", "post"]),
        (
            "/session/{sessionID}/message/{messageID}",
            &["get", "delete"],
        ),
        (
            "/session/{sessionID}/message/{messageID}/part/{partID}",
            &["patch", "delete"],
        ),
        ("/session/{sessionID}/prompt_async", &["post"]),
        ("/session/{sessionID}/init", &["post"]),
        ("/session/{sessionID}/command", &["post"]),
        ("/session/{sessionID}/shell", &["post"]),
        ("/session/{sessionID}/abort", &["post"]),
        ("/session/{sessionID}/revert", &["post"]),
        ("/session/{sessionID}/unrevert", &["post"]),
        ("/session/{sessionID}/share", &["post", "delete"]),
        ("/session/{sessionID}/summarize", &["post"]),
        ("/session/{sessionID}/permissions/{permissionID}", &["post"]),
        ("/experimental/capabilities", &["get"]),
        ("/experimental/console", &["get"]),
        ("/experimental/console/orgs", &["get"]),
        ("/experimental/console/switch", &["post"]),
        ("/experimental/workspace/adapter", &["get"]),
        ("/experimental/workspace", &["get", "post"]),
        ("/experimental/workspace/status", &["get"]),
        ("/experimental/workspace/sync-list", &["post"]),
        ("/experimental/workspace/warp", &["post"]),
        ("/experimental/workspace/{id}", &["delete"]),
        ("/experimental/control-plane/move-session", &["post"]),
        ("/experimental/worktree", &["get", "post", "delete"]),
        ("/experimental/worktree/reset", &["post"]),
        (
            "/experimental/project/{projectID}/copy",
            &["post", "delete"],
        ),
        ("/experimental/project/{projectID}/copy/refresh", &["post"]),
        (
            "/experimental/project/{projectID}/copy/generate-name",
            &["post"],
        ),
        ("/experimental/tool", &["get"]),
        ("/experimental/tool/ids", &["get"]),
        ("/experimental/session", &["get"]),
        ("/experimental/session/{sessionID}/background", &["post"]),
        ("/experimental/resource", &["get"]),
        ("/sync/history", &["post"]),
        ("/sync/replay", &["post"]),
        ("/sync/steal", &["post"]),
        ("/sync/start", &["post"]),
        ("/tui/publish", &["post"]),
        ("/tui/append-prompt", &["post"]),
        ("/tui/open-help", &["post"]),
        ("/tui/open-sessions", &["post"]),
        ("/tui/open-themes", &["post"]),
        ("/tui/open-models", &["post"]),
        ("/tui/submit-prompt", &["post"]),
        ("/tui/clear-prompt", &["post"]),
        ("/tui/execute-command", &["post"]),
        ("/tui/show-toast", &["post"]),
        ("/tui/select-session", &["post"]),
        ("/tui/control/next", &["get"]),
        ("/tui/control/response", &["post"]),
        ("/api/health", &["get"]),
        ("/api/location", &["get"]),
        ("/api/agent", &["get"]),
        ("/api/command", &["get"]),
        ("/api/skill", &["get"]),
        ("/api/reference", &["get"]),
        ("/api/integration", &["get"]),
        ("/api/integration/{integrationID}", &["get"]),
        ("/api/integration/{integrationID}/connect/key", &["post"]),
        ("/api/integration/{integrationID}/connect/oauth", &["post"]),
        ("/api/integration/attempt/{attemptID}", &["get", "delete"]),
        ("/api/integration/attempt/{attemptID}/complete", &["post"]),
        ("/api/credential/{credentialID}", &["patch", "delete"]),
        ("/api/provider", &["get"]),
        ("/api/provider/{providerID}", &["get"]),
        ("/api/model", &["get"]),
        ("/api/event", &["get"]),
        ("/api/fs/read/*", &["get"]),
        ("/api/fs/list", &["get"]),
        ("/api/fs/find", &["get"]),
        ("/api/permission/request", &["get"]),
        ("/api/permission/saved", &["get"]),
        ("/api/permission/saved/{id}", &["delete"]),
        ("/api/question/request", &["get"]),
        ("/api/session", &["get", "post"]),
        ("/api/session/{sessionID}", &["get", "patch", "delete"]),
        ("/api/session/{sessionID}/agent", &["post"]),
        ("/api/session/{sessionID}/model", &["post"]),
        ("/api/session/{sessionID}/context", &["get"]),
        ("/api/session/{sessionID}/message", &["get"]),
        ("/api/session/{sessionID}/message/{messageID}", &["get"]),
        ("/api/session/{sessionID}/permission", &["get"]),
        (
            "/api/session/{sessionID}/permission/{requestID}/reply",
            &["post"],
        ),
        ("/api/session/{sessionID}/question", &["get"]),
        (
            "/api/session/{sessionID}/question/{requestID}/reply",
            &["post"],
        ),
        (
            "/api/session/{sessionID}/question/{requestID}/reject",
            &["post"],
        ),
        ("/api/session/{sessionID}/prompt", &["post"]),
        ("/api/session/{sessionID}/command", &["post"]),
        ("/api/session/{sessionID}/shell", &["post"]),
        ("/api/session/{sessionID}/init", &["post"]),
        ("/api/session/{sessionID}/compact", &["post"]),
        ("/api/session/{sessionID}/wait", &["post"]),
        ("/api/pty/shells", &["get"]),
        ("/api/pty", &["get", "post"]),
        ("/api/pty/{ptyID}", &["get", "put", "delete"]),
        ("/api/pty/{ptyID}/connect-token", &["post"]),
        ("/api/pty/{ptyID}/connect", &["get"]),
    ]);
    Json(json!({
        "openapi": "3.1.0",
        "info": {
            "title": "hya OpenCode compatibility API",
            "version": env!("CARGO_PKG_VERSION"),
        },
        "paths": paths,
    }))
}

fn paths(entries: &[(&str, &[&str])]) -> Value {
    Value::Object(
        entries
            .iter()
            .map(|(path, methods)| ((*path).to_string(), methods_map(methods)))
            .collect(),
    )
}

fn methods_map(methods: &[&str]) -> Value {
    Value::Object(
        methods
            .iter()
            .map(|method| ((*method).to_string(), Value::Object(Map::new())))
            .collect(),
    )
}
